M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Mi 15 Mär 2023 01:56:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-15T01:56:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
%
G90
G05
T1
X75.66Y-54.45
T0
M30
